export GNUPGHOME="$HOME/.local/share/gnupg"
export WAKATIME_HOME="$HOME/.config/wakatime"
export OLLAMA_MODELS="$HOME/.local/share/ollama/models"
export ANDROID_SDK_HOME="$HOME/.local/share/android"
export ANDROID_AVD_HOME="$HOME/.local/share/android/avd"
export NUGET_PACKAGES="$HOME/.cache/NuGetPackages"
export DOTNET_CLI_HOME="$HOME/.local/share/dotnet-cli"
export PATH="$PATH:$HOME/.dotnet/tools"
