#################
### AUTOSTART ###
#################

exec-once = hyprlock & hypridle
exec-once = ashell & hyprpaper 
exec-once = v2rayn
#exec-once = feh 'https://tenor.com/view/cat-cat-sucking-on-finger-cat-sucking-kitty-kitty-sucking-on-finger-gif-16253711665381478420'
