general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    brightness = 0.3
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "<span background='##1c1c1c'>[ $(date +"%d-%m-%Y %H:%M:%S") ]</span>"
    color = rgb(255, 255, 255)
    font_size = 12
    font_family = monospace
    position = 0, 70
    halign = center
    valign = center
    zindex = 1
}

# Box Outline
shape {
    monitor =
    size = 400, 180
    color = rgba(0, 0, 0, 0.0)
    border_size = 2
    border_color = rgb(255, 255, 255)
    rounding = 0
    position = 0, -20
    halign = center
    valign = center
}

# System Prompt
label {
    monitor =
    text = <span font_family="monospace" foreground="##ffffff">$USER@tty1:~$ unlock-session</span>
    color = rgb(255, 255, 255)
    font_size = 12
    font_family = monospace
    position = -5, 30
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 45
    outline_thickness = 1
    dots_size = 0.4
    dots_spacing = 0.2
    dots_center = false
    outer_color = rgb(255, 255, 255)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <span font_family="monospace" foreground="##ffffff">█                                 </span>
    hide_input = false
    position = 0, -40
    halign = center
    valign = center
    rounding = 0
    dots_text_format = *
}

# Keyboard Layout
label {
    monitor =
    text = <span background='##1c1c1c'>[ $LAYOUT[en,ru] ]</span>
    font_size = 12
    font_family = monospace
    position = 0, -110
    halign = center
    valign = center
    zindex = 1
}


