[appearance.animations]
enabled = true
menu_fade_duration_ms = 200

[appearance]
scale_factor = 1.1

[appearance.menu]
backdrop = 0.3

[modules]
left = [ "Workspaces", "Tray" ]
center = [ "WindowTitle" ]
right = [["Updates"], ["KeyboardLayout"], ["Tempo", "Privacy", "Settings"], "appLauncher"]
