[appearance.animations]
enabled = true
menu_fade_duration_ms = 200

[appearance]
scale_factor = 1.1

[appearance.menu]
backdrop = 0.3

[modules]
left = [ "Workspaces", "Tray" ]
center = [ "WindowTitle" ]
right = [["Updates"], ["KeyboardLayout"], ["Tempo", "Privacy", "Settings"], "appLauncher"]

[updates]
check_cmd = "checkupdates 2>/dev/null; yay -Qua 2>/dev/null | sort -u"
update_cmd = 'kitty fish -c "update; echo; echo Done - Press enter to exit; read" &'

interval = 3600

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "tofi-drun --drun-launch=true"
